FROM eclipse-temurin:21_35-jdk
MAINTAINER com.ntt-data.hpc.cloud.sample
COPY target/NTT-Data-HPC-Cloud-Sample-0.0.1-SNAPSHOT.jar ntt-cloud-Sample-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ntt-cloud-Sample-0.0.1-SNAPSHOT.jar"]